---

- hosts: all
  vars:
    ansible_ssh_pipelining: true
  gather_facts: true

- hosts: kube-master
  roles:
    - { role: remove-node/pre-remove, tags: pre-remove }

- hosts: "{{ node | default('kube-node') }}"
  roles:
    - { role: kubespray-defaults }
    - { role: reset, tags: reset }

- hosts: kube-master
  roles:
    - { role: remove-node/post-remove, tags: post-remove }
